Validate Hiera values
simp/rubygem-simp-scelint pull request #20
Opened 2022-10-07 21:22 UTC by silug

* Add methods for retrieving profile names and confines
* Compile data the way that compliance_markup does and validate the results
* Handle a few error cases

Fixes #14

2022-10-12 15:55 UTC, michael-riddle requested changes
Let's error out with duplicate parameters with different values. I don't think duplicate parameters setting the same value warrant a warning.

2022-10-12 15:55 UTC, michael-riddle commented on lib/scelint.rb
> +            warnings << [
We should change this to add the value to the array only if the new setting is different than the old one. We should change also change it to an error rather than a warning of that condition is met. This would be the more appropriate behavior for this type of test in my opinion.

2022-10-12 16:51 UTC, silug commented
Historically, `errors` meant things that would make `compliance_markup` fall over, and `warnings` were everything else.  That's not exactly as granular as one might like, so I've added `notes`, but right now there is no real difference between `notes` and `warnings`. I think i need to:
- add option parsing to the script
- make the expensive validation pass opt-out
- add a way to suppress output for the `notes`
- add an option to make `warnings` fatal

2022-10-12 17:33 UTC, michael-riddle commented
Something isn't working as expected. The errors I'm getting point to rsyslog::tls_tcp_server being set to false from true, however, the checks that control that parameter are only mapped to enabled for el8 and only mapped to disabled for el7. This also doesn't appear to be finding some values I was expecting to show up in the list of failures such as useradd::useradd::inactive (same ces mapped to the values of 0, 30, 35, and 90) in rhel 8.

2022-10-12 18:25 UTC, michael-riddle commented
> Historically, `errors` meant things that would make `compliance_markup` fall over, and `warnings` were everything else. That's not exactly as granular as one might like, so I've added `notes`, but right now there is no real difference between `notes` and `warnings`. I think i need to:
> 
> * add option parsing to the script
> * make the expensive validation pass opt-out
> * add a way to suppress output for the `notes`
> * add an option to make `warnings` fatal

#23, #24, #25, and #26 created to address these.

2024-10-30 19:47 UTC, michael-riddle approved these changes

2024-10-30 19:51 UTC, merged